# Generated by Django 4.2.6 on 2023-12-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('due', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=30)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'db_table': 'BillSupplier',
            },
        ),
    ]
