# Generated by Django 4.2.6 on 2023-12-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
        ('rawmaterials', '0002_alter_rawmaterial_price_alter_rawmaterial_quantity_and_more'),
        ('rawmaterials_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawMaterial_Product',
            new_name='RawMaterialProduct',
        ),
        migrations.AlterModelTable(
            name='rawmaterialproduct',
            table='RawMaterialProduct',
        ),
    ]
