# Generated by Django 4.2.6 on 2023-12-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
        ('rawmaterials', '0002_alter_rawmaterial_price_alter_rawmaterial_quantity_and_more'),
        ('rawmaterials_products', '0002_rename_rawmaterial_product_rawmaterialproduct_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterialproduct',
            unique_together={('product', 'raw_material')},
        ),
    ]
