# Generated by Django 4.2.6 on 2023-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='here you can insert your Category name', max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('notes', models.TextField()),
            ],
        ),
    ]
