# Generated by Django 4.2.6 on 2023-10-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='notes',
        ),
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
