# Generated by Django 4.2.6 on 2023-12-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='Table',
        ),
    ]
