# Generated by Django 4.2.6 on 2023-12-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='capacity',
        ),
    ]
